<a href="https://colab.research.google.com/github/tec03/ParaAssignment01-/blob/main/assignment01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Module 5
## Alejandra Guadalupe Larrañaga Altamirano - A01794334
### Numpy 1D Arrays

Numpy is a library for scientific computing. It has many useful functions. There are many other advantages like speed an memory. Numpy is also the basis for pandas

In [ ]:
a = ["0",1,"two","3",4]


A Python list is a container that allows you to store and access data. Each element is
associated with an index. We can access each element using a square bracket, as follows.
-   A "numpy" array or "ndarray" is similar to a list. It's usually fixed in size and each
element is of the same type, in this case, integers. 
-   We can cast a list to a numpy arrayby first importing numpy. We then cast the list as follows. 
-   We can access the data via an index. As with a list, we can access each element with an integer and a square bracket.

In [2]:
import numpy as np

a=np.array([0,1,2,3,4])
type(a)

numpy.ndarray

In [2]:
a.dtype

dtype('int64')

In [3]:
a.size

5

In [4]:
a.ndim

1

-   The attribute "ndim” represents the number of array dimensions or the rank of the array, in this case one.
-   The attribute "shape” is a tuple of integers indicating the size of the array in each dimension.
-   We can create a numpy array with real numbers. When we check the type of the array, we get numpy.ndarray. 

In [5]:
a.shape

(5,)

### Indexing and Slicing methods

In [12]:
c=np.array([20,1,2,3,4])

c[0] = 100
c[4]=3
c

array([100,   1,   2,   3,   3])

Like lists and tuples, we can slice a numpy array. The elements of the array correspond
to the following index. 

In [14]:
d=c[1:4]
d

array([1, 2, 3])

We can assign the corresponding indexes to new values 

In [15]:
c[3:5] = 300,400
c

array([100,   1,   2, 300, 400])

## Basic Operations
### Vector Addition and Substraction

Vector addition is a widely used operation in data science. 
-   Consider the vector 'u' with two elements,  consider the vector 'v' with two components. 
-   In vector addition, we create a new vector in this case 'z'. 
-   The first component of 'z' is the addition of the first component of vectors 'u' and 'v'. 
-   Similarly, the second component is the sum of the second components of 'u' and 'v'. 
-   This new vector 'z' is now a linear combination of the vector 'u' and 'v'. Representing vector addition with line segment or arrows is helpful.

In [18]:
u = [1,0]
v = [1,0]
z=[]

for n,m in zip(u,z):
    z.append(n+m)

u=np.array([1,0])
v=np.array([0,1])

z=u+v
z

array([1, 1])

We can also perform vector subtraction by changing the addition sign to a subtraction sign. It would require multiple lines to perform vector subtraction on two lists

In [19]:
z=u-v
z

array([ 1, -1])

## Array multiplication with a Scalar
-   Vector multiplication with a Scalar is another commonly performed operation
-   Vector multiplication with a scalar only requires one line of code using Numpy.
-   It would require multiple lines to perform the same task as shown with python lists, the operation would also be much slower

In [20]:
y = np.array([1,2])
z=2*y
z

array([2, 4])

In [21]:
u = np.array([1,2])
v = np.array([3,2])

z=u*v
z

array([3, 4])

## Dot Product

-   The dot product is a single number given by the following term and represents how similar two vectors are. We multiply the first component from 'v' and 'u'. 
-   We then multiply the second component and add the result together.
-   The result is a number that represents how similar the two vectors are.
-   Consider the array 'u'. The array contains the following elements. 
-   If we add a scalar value to the array, numpy will add that value to each element. This property is known as broadcasting.

In [23]:
u=np.array([1,2,3,-1])
z=u+1
z

array([2, 3, 4, 0])

## Universal Functions

-   A universal function is a function that operates on ndarrays.
-   We can apply a universal function to a Numpy array.

In [4]:
a = np.array([90,115,110])
mean_a=a.mean()
print(mean_a)
b = np.array([1,-2,3,4,5])
max_b=b.max()
max_b

105.0


5

We can use numpy to create functions that map numpy arrays to new numpy arrays.

In [30]:
np.pi
x = np.array([0,np.pi/2,np.pi])
y=np.sin(x)
y

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

-   A useful function for plotting mathematical functions is "linespace". Linespace returns
evenly spaced numbers over a specified interval. 
-   We specify the starting point of the sequence.
-   The ending point of the sequence. The parameter "num" indicates the Number of samples to generate

In [32]:
np.linspace(-2,2,num=5)
np.linspace(-2,2,num=9)

array([-2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ])

### Plotting Mathematical Functional

-   We can use the function linespace to generate 100 evenly spaced samples from the interval 0 to 2 pi. \
-   We can use the Numpy function sine to map the array x to a new array y. 
-   We can import the library pyplot as plt to help us plot the function.

In [5]:
x = np.linspace(0,2*np.pi,100)
y = np.sin(x)

import matplotlib.pyplot as plt
%matplotlib inline
plt.plot(x,y)

ModuleNotFoundError: No module named 'matplotlib'

In [36]:
np.array([1,-1])*np.array([1,1])

array([ 1, -1])

In [37]:
np.dot(np.array([1,-1]),np.array([1,1]))

0

In [40]:
c = np.array([-10, 201, 43, 94, 502])

max_value = c.max()
min_value = c.min()
sum = (max_value + min_value)

sum

492

In [41]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

res = np.subtract(arr1, arr2)
res

array([-10,  -1,   8,  17,  26,  35])

In [43]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([2, 1, 2, 3, 4, 5])

res = np.multiply(arr1, arr2)

In [44]:
arr1 = np.array([3, 5])
arr2 = np.array([2, 4])

np.dot(arr1, arr2)

26

In [46]:
arr = np.array([1, 2, 3, -1]) 

new = arr + 5
new

array([6, 7, 8, 4])

In [48]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([1, 0, 1, 0, 1])
arr1 * arr2 

array([1, 0, 3, 0, 5])

## Numpy 2D Arrays

-   We can create Numpy arrays with more than one dimension.
-   

In [50]:
a = [[11,12,13],[21,22,23],[31,32,33]]

A = np.array(a)

A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

-  We can use the attribute "ndim" to obtain the number of axes or dimensions referred to as the rank.
-  The term rank does not refer to the number of linearly independent columns like a matrix.
-  It's useful to think of "ndim" as the number of nested lists.
-  The first list represents the first dimension.
-  This list contains another set of lists.
-  This represents the second dimension or axes.
-  The number of lists the list contains does not have to do with the dimension but the shape of the list.
-  As with the 1d array, the attribute "shape" returns a tuple.
-   The first element in the tuple corresponds to the number of nested lists contained in
the original list or the number of rows in the rectangular representation, the second element corresponds to the size of each of the nested lists or the number of columns in the rectangular array 0

In [53]:
A.ndim
A.shape
A.size

9

We can also use the attribute size to get the size of the array, we see there are three rows and three columns. Multiplying the number of columns and rows together we get the total number of elements

-   We can use rectangular brackets to access the different elements of the array.
-   The index in the first bracket corresponds to the different nested lists, each a different
color.
-   The second bracket corresponds to the index of a particular element within the nested list.
-   Using the rectangular representation, the first index corresponds to the row index.
-   The second index corresponds to the column index.
-   We can also use a single bracket to access the elements as follows.
-   Consider the following syntax:

In [60]:
A = [[11,12,13],[21,22,23],[31,32,33]]
A[1][2]
A[0][0]

11

-   We can also use slicing in numpy arrays.
-   The first index corresponds to the first row.
-   The second index accesses the first two columns.


-   To add two arrays in numpy we define the array in this case X.
-   Then we define the second array Y.We add the arrays.
-   The result is identical to matrix addition.
-   Multiplying a Numpy array by a scalar is identical to multiplying a matrix by a scalar.
-   Consider the matrix Y, if we multiply the matrix by the scalar 2 we simply multiply every element in the matrix by 2.
-   The result is a new matrix of the same size where each element is multiplied by two.
-   Consider the array y; we first define the array.
-   We multiply the array by a scalar as follows and assign it to the variable Z.
-   -   The result is a new array where each element is multiplied by two.
-   Multiplication of two arrays corresponds to an element-wise product or Hadamard product.

In [62]:
Y = np.array([[2,1],[1,2]])
Z = 2*Y
z

array([2, 3, 4, 0])

Hadamard product corresponds to multiplying each of the elements in the same position

In [64]:
X = np.array([[1,0],[0,1]])
Y = np.array([[2,1],[1,2]])

Z=X*Y
Z

array([[2, 0],
       [0, 2]])

We can also perform matrix multiplication with numpy arrays.

In [6]:
A=np.array([[0,1,1],[1,0,1]])
B=np.array([[1,1],[1,1],[-1,1]])
C=np.dot(A,B) #It corresponds to the matrix multiplication of array "A" and "B".
C

array([[0, 2],
       [0, 2]])

## Simple APIs 

An API lets two pieces of software talk to each other.
You use the API to communicate with the API via inputs and outputs.


In [8]:
import pandas as pd

dict_ = { 'a':[11,21,31], 'b':[12,22,32]}

df = pd.DataFrame(dict_)

ModuleNotFoundError: No module named 'pandas'

We use the pandas API to process the data by communicating with the other Software Components.

## REST APIs

REST APIs are another popular type of API; they allow you to communicate through theinternet allowing you to take advantage of resources like storage, access more data, artificial intelligent algorithms, and much more.

-   REST APIs are used to interact with web services, Applications that you call through the internet
-   They have set of Rules regarding:
    1.  Communication
    2.  Input or Request
    3.  Output or Response

HTTP methods are a way of transmitting data over the internet.
-   The HTTP message usually contains a JSON file. This contains instructions for what operation
we would like the service to perform. 

An API key is a way to access the API. It’s a unique set of characters that the API uses to identify you and authorize you. Usually your first call to the API includes the API key. This will allow you access to the API.

In [9]:
from ibm_watson import SpeechToTextV1

url_s2t="https://stream.watsonplatform.net/speech-to-text/api"

iam_apikey_s2t="EOeiZxxxDxV2xxxxxxxxxxxxxxxxxjYen9SKARKW-"

s2t=SpeechToTextV1(iam_apikey=iam_apikey_s2t, url=url_s2t)

filename = 'hello_this_is_python.wav'

with open(filename,mode="rb") as wav:
    response = s2t.recognize(audio=wav,content_type='audio/wav')

response.result



ModuleNotFoundError: No module named 'ibm_watson'

In [ ]:
from ibm_watson import LanguageTranslatorV3

url_lt='https://gateway.watsonplatform.net/language-translator/api'

apikey_lt="dU2SaxxxxxxxxxxxxxasdfCuasdf"

version_lt='2018-05-01'

language_translator = LanguageTranslatorV3(iam_apikey=apikey_lt, url=url_lt,version=version_lt)

language_translator.list_identifiable_languages().get_result()

In [ ]:
recognized_text='hello this is python'

translation_response=language_translator.translate(text=recognized_text,model_id='en-es')

translation = translation_response.get_result()

spanish_translation = translation['translations'][0]['translation']